### ISSUE TITLE
Julia Branch To-Do

### ISSUE THREAD

**Issue by rbartelme** [genophenoenvo/docker#1]
## Things to do with RStudio ML/Julia Build

Docker image builds and container runs on local machine.

- [x] Merge Julia Branch to GenoPhenoEvo Docker master
- [x] Push to CyVerse VICE Dockerhub
- [x] Test on CyVerse DE

**Comment by dlebauer** [comment]
all done, tyson is spinning up container and testing / under review. Will generate test data for running scripts - will be done in issue #3
